/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c19",
        "inverse-surface": "#30312e",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#a6c8ff",
        "surface": "#fbf9f4",
        "secondary-fixed": "#ffdbc9",
        "primary-fixed": "#d5e3ff",
        "surface-container-low": "#f5f3ee",
        "on-tertiary-fixed": "#221b00",
        "surface-container": "#f0eee9",
        "tertiary": "#705d00",
        "outline": "#737781",
        "primary": "#003466",
        "on-secondary-fixed": "#321200",
        "on-primary-fixed": "#001c3b",
        "on-secondary-container": "#783603",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#a6c8ff",
        "secondary-fixed-dim": "#ffb68c",
        "surface-dim": "#dbdad5",
        "surface-container-high": "#eae8e3",
        "error-container": "#ffdad6",
        "on-surface": "#1b1c19",
        "surface-bright": "#fbf9f4",
        "surface-container-highest": "#e4e2dd",
        "primary-container": "#1a4b84",
        "surface-tint": "#335f99",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#4c3e00",
        "on-primary-container": "#93bcfc",
        "on-tertiary-fixed-variant": "#544600",
        "inverse-on-surface": "#f2f1ec",
        "on-secondary-fixed-variant": "#753401",
        "on-surface-variant": "#424750",
        "tertiary-container": "#c9a900",
        "error": "#ba1a1a",
        "background": "#fbf9f4",
        "outline-variant": "#c3c6d1",
        "tertiary-fixed": "#ffe16d",
        "on-secondary": "#ffffff",
        "surface-variant": "#e4e2dd",
        "on-tertiary": "#ffffff",
        "secondary": "#934b19",
        "on-primary-fixed-variant": "#144780",
        "tertiary-fixed-dim": "#e9c400",
        "secondary-container": "#ffa26a",
        "jugaad-blue": "#1A4B84",
        "jugaad-yellow": "#FFD700",
        "jugaad-beige": "#f4f1ea",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        annotation: ["cursive"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      spacing: {
        lg: "24px",
        xl: "40px",
        margin: "20px",
        base: "4px",
        gutter: "16px",
        sm: "8px",
        xs: "4px",
        md: "16px"
      },
      boxShadow: {
        'jugaad': '4px 4px 0px 0px rgba(26, 75, 132, 1)',
        'jugaad-black': '2px 2px 0px 0px rgba(0, 0, 0, 1)',
        'jugaad-lg': '6px 6px 0px 0px rgba(0, 0, 0, 1)',
        'jugaad-blue-lg': '6px 6px 0px 0px rgba(26, 75, 132, 1)',
      }
    },
  },
  plugins: [],
}
