import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import usePageTitle from '../hooks/usePageTitle';

const BAZAARI_KEY = 'jg_bazaari';

// Source → dealer type label
const SOURCE_LABELS = {
  kabadiwala: 'Kabadi-wala / Scrap Dealer',
  hardware_store: 'Hardware Store',
  agriculture_shop: 'Agriculture / Krishi Shop',
  free: 'Free / Found Locally',
  pharmacy: 'Medical Store',
  other: 'General Market',
};

// Static dummy dealers by source type
const DEALERS = {
  kabadiwala: [
    { name: 'Sharma Scrap Centre', area: 'Near Old Bus Stand', dist: '0.8 km', open: true },
    { name: 'Gupta Junk Yard', area: 'Industrial Estate, Plot 42', dist: '1.4 km', open: true },
    { name: 'Raju Kabadi Store', area: 'Old Mandi Road', dist: '2.1 km', open: false },
  ],
  hardware_store: [
    { name: 'Balaji Hardware', area: 'Main Market, Shop 7', dist: '0.5 km', open: true },
    { name: 'Modern Alloys & Tools', area: 'Bypass Junction', dist: '1.9 km', open: true },
    { name: 'Laxmi Building Supplies', area: 'Civil Lines', dist: '3.2 km', open: false },
  ],
  agriculture_shop: [
    { name: 'Kisan Seva Kendra', area: 'Near Gram Panchayat', dist: '0.6 km', open: true },
    { name: 'Agro Mart', area: 'Highway Road', dist: '2.4 km', open: true },
  ],
  free: [],
  other: [
    { name: 'Mandi / Weekly Bazaar', area: 'Town Centre', dist: '1.0 km', open: true },
    { name: 'District Supply Store', area: 'Civil Lines', dist: '2.8 km', open: false },
  ],
};

function getDealersForMaterials(materials) {
  const sources = new Set(materials.map(m => m.source || 'other').filter(s => s !== 'free'));
  const primarySource = [...sources][0] || 'other';
  return { source: primarySource, dealers: DEALERS[primarySource] || DEALERS.other };
}

function generateBillNo() {
  return 'BZR-' + Math.floor(1000 + Math.random() * 9000);
}

const Bazaari = () => {
  usePageTitle('Bazaari');
  const [data, setData] = useState(null);
  const [billNo] = useState(generateBillNo);

  useEffect(() => {
    const raw = localStorage.getItem(BAZAARI_KEY);
    if (raw) {
      try { setData(JSON.parse(raw)); } catch { /* ignore */ }
    }
  }, []);

  const handlePrint = () => window.print();

  const handleWhatsApp = () => {
    if (!data) return;
    const lines = [
      `📋 *Bill of Materials — ${data.title}*`,
      '',
      ...data.materials.map(m => `• ${m.item} (${m.quantity}) — ₹${m.cost_inr?.toFixed(0)}`),
      '',
      `*Total: ₹${data.total_cost_inr?.toFixed(0)}*`,
      '',
      'Generated by JugaadGPT 🔧',
    ];
    const text = encodeURIComponent(lines.join('\n'));
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  if (!data) {
    return (
      <main style={{ maxWidth: 680, margin: '0 auto', padding: '40px 20px 120px', textAlign: 'center' }}>
        <div style={{ fontSize: 48, marginBottom: 16 }}>🛒</div>
        <div style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: 24, textTransform: 'uppercase', marginBottom: 12 }}>
          Bazaari is Empty
        </div>
        <p style={{ fontSize: 14, color: '#828B99', lineHeight: 1.6, marginBottom: 24 }}>
          Get a solution in the Workshop first. When a solution arrives, click <strong>"View in Bazaari"</strong> to see the Bill of Materials here.
        </p>
        <Link to="/" style={{
          display: 'inline-block', background: '#FFD700', color: '#0E1B2D',
          padding: '10px 24px', fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700, textTransform: 'uppercase', textDecoration: 'none',
          border: '2px solid #0E1B2D', fontSize: 13,
        }}>
          ← Back to Workshop
        </Link>
      </main>
    );
  }

  const { dealers, source } = getDealersForMaterials(data.materials);
  const sourceLabel = SOURCE_LABELS[source] || 'Local Market';
  const savedDate = data.savedAt ? new Date(data.savedAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '';

  return (
    <main style={{ maxWidth: 700, margin: '0 auto', padding: '20px 16px 140px', fontFamily: "'Inter', sans-serif" }}>

      {/* Bill Header */}
      <div style={{
        background: '#fff', border: '3px solid #0E1B2D',
        boxShadow: '5px 5px 0 #0E1B2D', marginBottom: 24,
        position: 'relative', overflow: 'hidden',
      }} className="print-section">

        {/* Duct tape corners decoration */}
        <div style={{ position: 'absolute', top: -8, left: 24, width: 60, height: 16, background: '#C1A87D', opacity: 0.7, transform: 'rotate(-1deg)', zIndex: 2 }} />
        <div style={{ position: 'absolute', top: -8, right: 24, width: 60, height: 16, background: '#C1A87D', opacity: 0.7, transform: 'rotate(1deg)', zIndex: 2 }} />

        {/* Navy top bar */}
        <div style={{ background: '#1A4B84', padding: '14px 20px 10px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
          <div>
            <div style={{ color: '#FFD700', fontFamily: "'Archivo Black', sans-serif", fontSize: 28, textTransform: 'uppercase', letterSpacing: '0.02em', lineHeight: 1 }}>
              Bill of Materials
            </div>
            <div style={{ color: '#fff', fontSize: 12, fontFamily: 'JetBrains Mono, monospace', marginTop: 4, opacity: 0.9, textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Project: {data.title}
            </div>
          </div>
          <div style={{ background: '#FFD700', border: '2px solid #fff', padding: '6px 12px', textAlign: 'center', minWidth: 120 }}>
            <div style={{ fontSize: 9, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#0E1B2D', marginBottom: 2 }}>
              Bill No.
            </div>
            <div style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: 22, color: '#0E1B2D', letterSpacing: '0.05em' }}>
              #{billNo}
            </div>
            <div style={{ fontSize: 9, fontFamily: 'JetBrains Mono, monospace', color: '#4A5568' }}>{savedDate}</div>
          </div>
        </div>

        {/* Ledger table */}
        <div style={{ padding: '0 20px 20px' }}>
          <div style={{
            background: '#1A4B84', color: '#fff',
            display: 'grid', gridTemplateColumns: '1fr 140px 140px',
            padding: '8px 12px', marginTop: 16,
            fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em',
          }}>
            <span>Material</span>
            <span>Quantity</span>
            <span style={{ textAlign: 'right' }}>Est. Price (₹)</span>
          </div>

          {data.materials.map((m, i) => (
            <div key={i} style={{
              display: 'grid', gridTemplateColumns: '1fr 140px 140px',
              padding: '10px 12px',
              borderBottom: '1px dashed #DFCCA9',
              background: i % 2 === 0 ? '#FAFAF8' : '#fff',
              fontSize: 13,
            }}>
              <span style={{ fontWeight: 500 }}>{m.item}</span>
              <span style={{ color: '#4A5568' }}>{m.quantity}</span>
              <span style={{ textAlign: 'right', fontFamily: 'JetBrains Mono, monospace', fontWeight: 600, color: '#1A4B84' }}>
                ₹ {m.cost_inr?.toLocaleString('en-IN')}
              </span>
            </div>
          ))}

          {/* Grand total */}
          <div style={{
            display: 'grid', gridTemplateColumns: '1fr 140px 140px',
            padding: '12px 12px', borderTop: '2px solid #0E1B2D', marginTop: 4,
            background: '#fff',
          }}>
            <span />
            <span style={{ fontSize: 11, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, textTransform: 'uppercase', alignSelf: 'center' }}>Grand Total</span>
            <span style={{ textAlign: 'right', fontFamily: "'Archivo Black', sans-serif", fontSize: 20, color: '#1A4B84' }}>
              ₹ {data.total_cost_inr?.toLocaleString('en-IN')}
            </span>
          </div>
        </div>
      </div>

      {/* Find at nearest dealer */}
      {dealers.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <span style={{ fontSize: 18 }}>📍</span>
            <div style={{ fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: '#0E1B2D' }}>
              Find at nearest {sourceLabel}
            </div>
          </div>

          <div style={{ display: 'grid', gap: 8 }}>
            {dealers.map((d, i) => (
              <div key={i} style={{
                background: '#fff', border: '1.5px solid #0E1B2D',
                padding: '12px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                boxShadow: '2px 2px 0 #0E1B2D',
              }}>
                <div>
                  <div style={{ fontWeight: 700, fontSize: 14 }}>{d.name}</div>
                  <div style={{ fontSize: 11, color: '#828B99', fontFamily: 'JetBrains Mono, monospace', textTransform: 'uppercase', marginTop: 2 }}>
                    {d.area}
                  </div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                  <span style={{
                    fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700,
                    padding: '2px 6px', background: d.open ? '#22c55e' : '#6b7280', color: '#fff',
                  }}>
                    {d.open ? 'OPEN' : 'CLOSED'}
                  </span>
                  <span style={{ fontSize: 12, fontFamily: 'JetBrains Mono, monospace', color: '#4A5568' }}>{d.dist}</span>
                </div>
              </div>
            ))}
          </div>

          {/* Jugaad tip */}
          <div style={{
            background: '#FFF9C4', border: '1.5px solid #C1A87D',
            padding: '12px 14px', marginTop: 12, fontSize: 12, lineHeight: 1.6,
            fontFamily: 'cursive', color: '#4A5568',
          }}>
            💡 <em>Jugaad tip: At kabadi-wala, ask for "grade scrap" for structural parts — it's salvaged from demolished factory beams and is much stronger than new local pipe.</em>
          </div>
        </div>
      )}

      {/* Action buttons */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
        <button
          onClick={handlePrint}
          style={{
            background: '#fff', color: '#0E1B2D', border: '2px solid #0E1B2D',
            padding: '14px', fontFamily: 'JetBrains Mono, monospace', fontWeight: 700,
            fontSize: 12, textTransform: 'uppercase', cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            boxShadow: '3px 3px 0 #0E1B2D',
          }}
        >
          📄 Share Bill PDF
        </button>
        <button
          onClick={handleWhatsApp}
          style={{
            background: '#FFD700', color: '#0E1B2D', border: '2px solid #0E1B2D',
            padding: '14px', fontFamily: 'JetBrains Mono, monospace', fontWeight: 700,
            fontSize: 12, textTransform: 'uppercase', cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            boxShadow: '3px 3px 0 #0E1B2D',
          }}
        >
          📲 Share on WhatsApp
        </button>
      </div>

      <style>{`
        @media print {
          body > *:not(main) { display: none !important; }
          .print-section { box-shadow: none !important; }
        }
      `}</style>
    </main>
  );
};

export default Bazaari;
